// <auto-generated />
namespace Cycle.Info.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init_twelve : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_twelve));
        
        string IMigrationMetadata.Id
        {
            get { return "201806131113145_init_twelve"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
