// <auto-generated />
namespace Cycle.Info.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init_one : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_one));
        
        string IMigrationMetadata.Id
        {
            get { return "201806101156318_init_one"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
